{% set version = "1.0.1" %}

package:
  name: libblitz
  version: {{ version }}

source:
  git_url: https://github.com/blitzpp/blitz.git
  git_rev: {{ version }}

build:
  number: 0
  skip: true  # [win and py27]
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python 2
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - test -d $PREFIX/include/blitz        # [unix]
    - test -e $PREFIX/lib/libblitz.a       # [unix]
    - test -e $PREFIX/lib/libblitz.so      # [linux]
    - test -e $PREFIX/lib/libblitz.dylib   # [osx]
    - if not exist %PREFIX%\Library\bin\blitz.dll exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\blitz.lib exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\pkgconfig\blitz.pc exit 1  # [win]
    - if not exist %PREFIX%\Library\include\blitz\blitz.h exit 1  # [win]
    - if not exist %PREFIX%\Library\include\blitz\ms\bzconfig.h exit 1  # [win]

about:
  home: https://sourceforge.net/projects/blitz
  license: LGPL 3
  summary: A C++ class library for scientific computing which provides performance on par with Fortran 77/90

extra:
  recipe-maintainers:
    - 183amir
