travis:
  secure:
    BINSTAR_TOKEN: gp5xDr2n3NPVC98e/YflO2+M10GPAcvRIRQh28+tUTGXB2crzjPxrFOuN89qgVv4+Htja2SOj+nOiQG6vuoEUSouRmMfdJ+9Ay31mjUYaQ2iHkDy0EFspICzl4gKcWwfCTN4Vm176O7Gw+5so5FiL+XzohMxASV6el7l6nIb45xy/StoOO92q6RWOsdgvGo3H3f49bp0EPs5StJiW3R5cpbqR7XPsaMqIJP8OU/AhKIBIHSkr679TeI8oJHQ0Atmvkvgg2XNj3u/0YQat4tT9I6Uhk6ip/IfhSq1P8ZLQ34oWSeS6qy0wJO9IhHwM3SN23JqwztBlaUEvwVuG/pZW+bpQ8oWAa8tpQXPAiuHmVagWbFxjZ+CDzyp42Wtk6I622n+QTCfT3M8bayw96QsgD2qeaAxY4TVwBTDPxdE7+apiEsW88Y0+U/KIlQtS+FbiBVhVDKccFmAdE78gL6doRT64As40UTOOVT7F0NYce+7xmUL22e7lf90KP/p4svNPSLXmqhTRAqkncUjjXMdvEPgIK/TegkTEp67SVPO4a6y4Sxo6thnMhmolWTCbfREdDf1yE8SAeR8XIxwK8NgkUe2z//f0kENADyyAnE3KMSWmHt12nKur1/GhxuyqVUlsCXJCsjJ6a87hHuKdqp8vq+BtQzcXgPy3PJj2d1mP3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
