travis:
  secure:
    BINSTAR_TOKEN: aeNwmmxMGj9O6b4TFoqVgqRReneEqxTnbdnayVsvdM3xWqdYVueKiphqCKoV8tKbIgvNEou+iJsjpwVyA9MQJ0niT7rKo4WErULOfzUeiA6N9fcMevmDMxmFYO8VlyDM2TXFhs7lXW0q6qW7AfCE1SRcHoCjZw4XQ1GfXcwRWQhRr27P2mTb2VgnhfTP5jT6NRwXFAl39Z1Xtff2CcOHTsXyGZ+By69hSN+M9xHMFqlLYZ/+ivfh/AmgDQzaG6jmX0yi4wD5QPemlT/Fo/aSpibcBla4lGtpg3HnADvZqq/zaO9/LhHPMuQO2KlxYwCRx5Dt9jBEQZbqNOLVQuKm3JsSPgmp7hwE1NP7mzjGSnOwR4lWpSHZJ9ohMc7ViIPXjKxjTQFeSKByrj+8F4+aKZPavlNpFyhsDR/mDJUd6yMMqplRT6fJBhOXKmVYcba8Ts/5VCmhNl3P+/rOLd4DeFqCPDbAzfyp0mIiDOob7RHOh4Qs1zG3VERMmiCDImaPoMKvllbrGsDOBnZ4gNFx5haxlJdoJHhlvvH16mLGfBppu67EL9gnEbCBF69Ukw5CcxwQSIacJ5+H24GZyV407siKd4AwlzdB4FS+j6+J051EKj23IL//BkVv+XoYqoDIeSEP3FBUdObNvmTCl9cCWn1wMYu2CPNPU6T4iIhjHbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
